export const JWT_SECRET = process.env.JWT_SECRET || "jwt_secret";
export const SALT_SECRET = parseInt(process.env.SALT_SECRET as string, 0) || 10;

export enum GameCommand {
	READY = "ready",
	UNREADY = "unready",
	PAUSE = "pause",
	UNPAUSE = "unpause",
	CONTINUE = "continue",
	CANCEL = "cancel",
	BACKUP = "backup",
	STAY = "stay",
	SWITCH = "switch",
}

export enum MsgEvent {
	CONNECT = "connection",
	DISCONNECT = "disconnect",
	MESSAGE = "message",
	IDENTITY = "identity",
	RCON = "rconSend",
	MATCHCMD = "matchCommand"
}

export enum MessageTypeRegex {
	ATTACKED = "\"(?<attackerName>.*)[<](?<attackerUserId>\\d+)[>][<](?<attackerSteamId>.*)[>][<](?<attackerTeam>CT|TERRORIST|Unassigned|Spectator)[>]\" \\[(?<attackerPosX>[-]?[0-9]+) (?<attackerPosY>[-]?[0-9]+) (?<attackerPosZ>[-]?[0-9]+)] attacked \"(?<victimName>.*)[<](?<victimUserId>\\d+)[>][<](?<victimSteamId>.*)[>][<](?<victimTeam>CT|TERRORIST|Unassigned|Spectator)[>]\" \\[(?<victimPosX>[-]?[0-9]+) (?<victimPosY>[-]?[0-9]+) (?<victimPosZ>[-]?[0-9]+)] with \"(?<attackerWeapon>[a-zA-Z0-9_]+)\" \\(damage \"(?<attackerDamage>[0-9]+)\"\\) \\(damage_armor \"(?<attackerDamageArmor>[0-9]+)\"\\) \\(health \"(?<victimHealth>[0-9]+)\"\\) \\(armor \"(?<victimArmor>[0-9]+)\"\\) \\(hitgroup \"(?<attackerHitGroup>.*)\"\\)",
	BOMB_DEFUSING = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>][<](?<user_team>CT|TERRORIST|Unassigned|Spectator)[>]\" triggered \"(Begin_Bomb_Defuse_With_Kit|Begin_Bomb_Defuse_Without_Kit)\"",
	BOMB_PLANTING = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>][<](?<user_team>CT|TERRORIST|Unassigned|Spectator)[>]\" triggered \"Planted_The_Bomb\"",
	MAP_CHANGING = "Loading map \"(?<maps>.*)\".*",
	MAP_CHANGED = "Started map \"(?<maps>.*)\".*",
	PLAYER_NAME_CHANGE = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>][<](?<user_team>CT|TERRORIST|Unassigned|Spectator)[>]\" changed name to \"(?<new_name>.*)\"",
	PLAYER_CONNECTED = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>][<][>]\" connected, address \"(?<address>.*)\"",
	PLAYER_DISCONNECTED = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>][<](?<user_team>CT|TERRORIST|Unassigned|Spectator)[>]\" disconnected",
	PLAYER_JOINED = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>][<][>]\" entered the game",
	PLAYER_GOT_BOMB = "triggered \\\"Got\_The\_Bomb\\\"",
	PLAYER_JOINED_TEAM = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>][<](?<user_team>CT|TERRORIST|Unassigned|Spectator)[>]\" joined team \"(?<join_team>CT|TERRORIST|Unassigned|Spectator)\"",
	KILL = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>][<](?<user_team>CT|TERRORIST|Unassigned|Spectator)[>]\" \\[(?<killer_x>[-]?[0-9]+) (?<killer_y>[-]?[0-9]+) (?<killer_z>[-]?[0-9]+)] killed \"(?<killed_user_name>.+)[<](?<killed_user_id>\\d+)[>][<](?<killed_steam_id>.*)[>][<](?<killed_user_team>CT|TERRORIST|Unassigned|Spectator)[>]\" \\[(?<killed_x>[-]?[0-9]+) (?<killed_y>[-]?[0-9]+) (?<killed_z>[-]?[0-9]+)] with \"(?<weapon>[a-zA-Z0-9_]+)\"(?<headshot>.*)",
	KILL_OTHER = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>][<](?<user_team>CT|TERRORIST|Unassigned|Spectator)[>]\" \\[(?<killer_x>[-]?[0-9]+) (?<killer_y>[-]?[0-9]+) (?<killer_z>[-]?[0-9]+)] killed other \"(?<object_name>.+)[<](?<object_id>\\d+)[>]\" \\[(?<killed_x>[-]?[0-9]+) (?<killed_y>[-]?[0-9]+) (?<killed_z>[-]?[0-9]+)] with \"(?<weapon>[a-zA-Z0-9_]+)\"(?<headshot>.*)",
	// KILL_ASSIST = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>][<](?<user_team>CT|TERRORIST|Unassigned|Spectator)[>]\" assisted killing \"(?<killed_user_name>.+)[<](?<killed_user_id>\d+)[>][<](?<killed_steam_id>.*)[>][<](?<killed_user_team>CT|TERRORIST|Unassigned|Spectator)[>]\"",
	PURCHASED = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>][<](?<user_team>CT|TERRORIST|Unassigned|Spectator)[>]\" purchased \"(?<object>.*)\"",
	ROUND_END = "World triggered \\\"Round_End\\\"",
	// ROUND_RESTART = "!World triggered \\\"Restart_Round_\((\d+)_(second|seconds)\)\\"!",
	ROUND_END_TRIGGERED = "Team \"(?<team>.*)\" triggered \"SFUI_Notice_(?<team_win>Terrorists_Win|CTs_Win|Target_Bombed|Target_Saved|Bomb_Defused)\" \\((?<team_one>.*) \\\"(?<team_one_score>\\d+)\\\"\\) \\((?<team_two>.*) \\\"(?<team_two_score>\\d+)\\\"\\)",
	ROUND_START = "World triggered \"Round_Start\"",
	MATCH_PAUSED = "Match pause is enabled",
	MATCH_UNPAUSED = "Match pause is disabled",
	MATCH_ENDED = "Game Over: competitive (?<map_group>.*) (?<map_name>.*) score (?<score_1>\\d+):(?<score_2>\\d+) after (?<match_time>\\d+) min",
	SAY = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>][<](?<user_team>CT|TERRORIST|Unassigned|Spectator)[>]\" say \"(?<text>.*)\"",
	SAY_TEAM = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>][<](?<user_team>CT|TERRORIST|Unassigned|Spectator)[>]\" say_team \"(?<text>.*)\"",
	TEAM_SWITCH = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>]\" switched from team [<](?<user_team>CT|TERRORIST|Unassigned|Spectator)[>] to [<](?<new_team>CT|TERRORIST|Unassigned|Spectator)[>]",
	TEAM_SCORED = "Team \"(?<team>CT|TERRORIST)\" scored \"(?<score>\\d+)\" with \"(?<players>\\d+)\" players",
	THREW_ITEM = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>][<](?<user_team>CT|TERRORIST|Unassigned|Spectator)[>]\" threw (?<stuff>hegrenade|flashbang|smokegrenade|decoy|molotov) \\[(?<pos_x>[-]?[0-9]+) (?<pos_y>[-]?[0-9]+) (?<pos_z>[-]?[0-9]+)]",
	LEFT_BUYZONE = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>][<](?<user_team>CT|TERRORIST|Unassigned|Spectator)[>]\" left buyzone with",
	PLAYER_DROPPED_BOMD = "\"(?<attackerName>.*)[<](?<attackerUserId>\\d+)[>][<](?<attackerSteamId>.*)[>][<](?<attackerTeam>CT|TERRORIST|Unassigned|Spectator)[>]\" triggered \"Dropped_The_Bomb\"",
	KILL_ASSIST = "\"(?<attackerName>.*)[<](?<attackerUserId>\\d+)[>][<](?<attackerSteamId>.*)[>][<](?<attackerTeam>CT|TERRORIST|Unassigned|Spectator)[>]\" assisted killing \"(?<victimName>.*)[<](?<victeamUserId>\\d+)[>][<](?<victimSteamId>.*)[>][<](?<victimTeam>CT|TERRORIST|Unassigned|Spectator)[>]\"",
	PLAYER_BLINDED = "\"(?<user_name>.+)[<](?<user_id>\\d+)[>][<](?<steam_id>.*)[>][<](?<user_team>CT|TERRORIST|Unassigned|Spectator)[>]\" blinded for (?<blind_sec>.*) by \"(?<victim_name>.+)[<](?<victim_id>\\d+)[>][<](?<victim_steam_id>.*)[>][<](?<victim_team>CT|TERRORIST|Unassigned|Spectator)[>]\" from flashbang",
	FREEZING_START = "Starting Freeze period",
}

export enum MessageType {
	ATTACKED = "ATTACKED",
	BOMB_DEFUSING = "BOMB_DEFUSING",
	BOMB_PLANTING = "BOMB_PLANTING",
	MAP_CHANGING = "MAP_CHANGING",
	MAP_CHANGED = "MAP_CHANGED",
	PLAYER_NAME_CHANGE = "PLAYER_NAME_CHANGE",
	PLAYER_CONNECTED = "PLAYER_CONNECTED",
	PLAYER_DISCONNECTED = "PLAYER_DISCONNECTED",
	PLAYER_JOINED = "PLAYER_JOINED",
	PLAYER_GOT_BOMB = "PLAYER_GOT_BOMB",
	PLAYER_JOINED_TEAM = "PLAYER_JOINED_TEAM",
	KILL = "KILL",
	KILL_OTHER = "KILL_OTHER",
	PURCHASED = "PURCHASED",
	ROUND_END = "ROUND_END",
	ROUND_END_TRIGGERED = "ROUND_END_TRIGGERED",
	ROUND_START = "ROUND_START",
	MATCH_PAUSED = "MATCH_PAUSED",
	MATCH_UNPAUSED = "MATCH_UNPAUSED",
	MATCH_ENDED = "MATCH_ENDED",
	SAY = "SAY",
	SAY_TEAM = "SAY_TEAM",
	TEAM_SWITCH = "TEAM_SWITCH",
	TEAM_SCORED = "TEAM_SCORED",
	THREW_ITEM = "THREW_ITEM",
	LEFT_BUYZONE = "LEFT_BUYZONE",
	PLAYER_DROPPED_BOMD = "PLAYER_DROPPED_BOMD",
	KILL_ASSIST = "KILL_ASSIST",
	PLAYER_BLINDED = "PLAYER_BLINDED",
	FREEZING_START = "FREEZING_START",
	UNKNOWN = "UNKNOWN",
	IGNORE = "IGNORE",
}

export enum MatchState {
	CREATED = 0,
	STARTING = 11,
	WAITING_START = 12,
	PLAYING = 13,
	PAUSED = 14,
	FINISHED = 15,
	CANCELLED = 16,
	WARMUP = 21,
	KNIFE = 22,
	END_KNIFE = 23,
	FIRST_SIDE = 34,
	SECOND_SIDE = 35,
	OT_FIRST_SIDE = 40,
	OT_SECOND_SIDE = 41,
	MATCH_PAUSED = 99,
	MATCH_UNPAUSED = 98,
}
