const Error = {
	NO_ERROR: 0,
	User: {
		// User: 2xx,
		EMAIL_NOT_EXISTS: 200,
		INVALID_CREDENTIALS: 201,
		ACCOUNT_NOT_EXISTS: 202,
		EMAIL_EXIST: 251,
		USERNAME_EXIST: 252,
	},
	Validate: {
		FULL_NAME_MUST_LONGER_THAN_SIX: 101,
		USERNAME_MUST_LONGER_THAN_SIX: 102,
		PASSWORD_MUST_LONGER_THAN_EIGHT: 103,
		EMAIL_MUST_LONGER_THAN_EIGHT: 104,
		EMAIL_EXIST: 105,
		USERNAME_EXIST: 106,
		TOKEN_INVALID: 1001,
	},
	System: {
		FAILED_GENERATE_IDENTITY: 1000
	}
};


export default Error;
